### ISSUE TITLE
Enhancement request -- ability to add customized tags

### ISSUE THREAD

**Issue by poorboy44** [DrSkippy/Gnip-Python-PowerTrack-Rules#2]
Hi DS team:

I'm trying to run some analysis for the D&B trial, and I'm using the Gnip-Python-PowerTrack-Rules package to create my json rules file for upload into historical power track.

One small feature enhancement that would be very useful would be the ability to add customized tags to the rules.  For example, I have a set of 10,000 rules (each corresponding to a business) and I 'd like the tag to be set to the rule itself, so I can easily enumerate the results afterwards.

The current ./create_rules.py -b option only accepts a parameter for a global tag (same for every rule in the set).

I tried using xargs but wasn't having much success.  Maybe I have an error in bash command?

cat ~/projects/20140617_DNB/dnbq2.rules | xargs -0 -I fn ./create_rules.py -o -b fn

Can you guys let me know if there's a way to do a bash command to  accomplish what I need?  If not, can you help me update the code to add an option to use the rule itself as the tag?

Thanks for your help!

Scotty

**Comment by DrSkippy** [comment]
If you create a tab delimited file with rule\tag you can feed them
directly into standard in.  For example, like this (there's a tab in there):

echo "my rule   my tag" | ./create_rules.py -o

> > > ===SHOWING LOCAL RULES -- May NOT RELECT SERVER STATUS===<<<

{"rules": [{"tag": "my tag", "value": "my rule"}]}

Very sorry! Poorly documented but useful feature.

On Mon, Jun 23, 2014 at 2:33 PM, Scotty Nelson notifications@github.com
wrote:

> Hi DS team:
> 
> I'm trying to run some analysis for the D&B trial, and I'm using the
> Gnip-Python-PowerTrack-Rules package to create my json rules file for
> upload into historical power track.
> 
> One small feature enhancement that would be very useful would be the
> ability to add customized tags to the rules. For example, I have a set of
> 10,000 rules (each corresponding to a business) and I 'd like the tag to be
> set to the rule itself, so I can easily enumerate the results afterwards.
> 
> The current ./create_rules.py -b option only accepts a parameter for a
> global tag (same for every rule in the set).
> 
> I tried using xargs but wasn't having much success. Maybe I have an error
> in bash command?
> 
> cat ~/projects/20140617_DNB/dnbq2.rules | xargs -0 -I fn ./create_rules.py
> -o -b fn
> 
> Can you guys let me know if there's a way to do a bash command to
> accomplish what I need? If not, can you help me update the code to add an
> option to use the rule itself as the tag?
> 
> Thanks for your help!
> 
> Scotty
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DrSkippy/Gnip-Python-PowerTrack-Rules/issues/2.

## 

Scott Hendrickson
303.219.0022
@drskippy27
       (transparency is the antidote for cynicism)
